### ISSUE TITLE
Add function via NooBaa Management Console fails...

### ISSUE THREAD

**Issue by msmiths** [noobaa/noobaa-core#6593]
### Environment info
- NooBaa Version:
```
INFO[0000] CLI version: 5.7.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:5.7.0       
INFO[0000] operator-image: noobaa/noobaa-operator:5.7.0 
```
- Platform: **OpenShift 4.7.4** - with NooBaa deployed via the OpenShift Container Storage operator.

### Actual behavior
1. Attempting to create a function via the NooBaa Management Console fails. A toast is displayed in the UI with the following message:
```
Creating function test failed
```

### Expected behavior
1. The function should be created successfully.

### Steps to reproduce
1. Open the **NooBaa Management Console**
2. Select **Functions** in the left hand navigation menu
3. Click the **Create Function** button
4. In the **Create Function** modal dialog, enter a **Function Name** of `test` and click the **Next** button
5. Enter the following function code:
```
function test() {
};
```
6. Enter `test` in the **Execution Function** field and click the **Next** button
7. Click the **Create** button
8. The error toast is displayed in the bottom left hand corner

### More information - Screenshots / Logs / Other output

The following message is seen in the logs for the `noobaa-core-0` pod:

```
[32mJun-21 9:29:17.796[35m [WebServer/36] [31m[ERROR][39m CONSOLE:: RPC._on_request: ERROR srv func_api.create_func reqid 366@wss://noobaa-mgmt-openshift-storage.apps.cp4wa-474-msmiths-ocs.cp.fyre.ibm.com(znszq7.zzwr) connid ws://[::ffff:10.254.12.1]:52574/(2g7zspo2o9) TypeError: Cannot read property 'openUploadStream' of null
    at /root/node_modules/noobaa-core/src/server/func_services/func_store.js:123:59
    at new Promise (<anonymous>)
    at FuncStore.create_code_gridfs (/root/node_modules/noobaa-core/src/server/func_services/func_store.js:122:16)
    at Object.create_func (/root/node_modules/noobaa-core/src/server/func_services/func_server.js:72:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /root/node_modules/noobaa-core/src/rpc/rpc.js:340:32
    at async RPC._on_request (/root/node_modules/noobaa-core/src/rpc/rpc.js:348:25)
```

**Comment by liranmauda** [comment]
Hi @msmiths 
I followed your reproduction steps but it worked for me.
I am using master.

Can you please reproduce it? and attach the logs? 
you can use the CLI command `noobaa diagnose` and attach the tar here.

Another thing is if it fails, can you refresh the browser page and retry?

**Comment by guymguym** [comment]
@liranmauda maybe related to mongo vs postgres?

**Comment by liranmauda** [comment]
@guymguym Following your suggestion I installed also master with mongo and it worked for me.

**Comment by msmiths** [comment]
@liranmauda I reproduced it and have attached the logs for the `noobaa-core-0` core pod: [log.txt](https://github.com/noobaa/noobaa-core/files/6725788/log.txt)

**Comment by msmiths** [comment]
@liranmauda I also tried running `noobaa diagnose` but I got the following output:

```
$ noobaa diagnose
INFO[0000] Running collection of diagnostics            
INFO[0028] ❌ No noobaa-db pods found\n
```

However, I can see the DB pod running in my environment... using Postgres:

```
$ oc get pods
NAME                                                              READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-2n8w2                                            3/3     Running   0          3d19h
csi-cephfsplugin-425tm                                            3/3     Running   0          3d20h
csi-cephfsplugin-6l8m6                                            3/3     Running   0          3d19h
csi-cephfsplugin-provisioner-5db9b8d549-cqj4j                     6/6     Running   14         3d20h
csi-cephfsplugin-provisioner-5db9b8d549-ppzfn                     6/6     Running   16         3d20h
csi-cephfsplugin-pz96m                                            3/3     Running   0          3d20h
csi-cephfsplugin-qng5g                                            3/3     Running   0          3d19h
csi-cephfsplugin-v4x25                                            3/3     Running   0          3d20h
csi-rbdplugin-5lrnp                                               3/3     Running   0          3d20h
csi-rbdplugin-76sgt                                               3/3     Running   0          3d19h
csi-rbdplugin-g72wp                                               3/3     Running   0          3d20h
csi-rbdplugin-jdxnq                                               3/3     Running   0          3d19h
csi-rbdplugin-provisioner-67fdfb4898-drpgl                        6/6     Running   17         3d20h
csi-rbdplugin-provisioner-67fdfb4898-nsxtr                        6/6     Running   13         3d20h
csi-rbdplugin-tbzgr                                               3/3     Running   0          3d20h
csi-rbdplugin-wwvk2                                               3/3     Running   0          3d19h
noobaa-core-0                                                     1/1     Running   0          5m46s
noobaa-db-pg-0                                                    1/1     Running   0          3d20h
noobaa-endpoint-5f6d9d7948-w7mtz                                  1/1     Running   0          3d20h
noobaa-operator-5f5d79fbc4-pqx6c                                  1/1     Running   7          3d20h
ocs-metrics-exporter-86f76b7577-cf59b                             1/1     Running   0          3d20h
ocs-operator-6cddc8b5c9-bz5dn                                     1/1     Running   5          3d20h
rook-ceph-crashcollector-ea294da11345bedb79386c958ae258ba-j82jr   1/1     Running   0          3d20h
rook-ceph-crashcollector-f49c62cf61a686d76a77a9e0704f7729-mpnvf   1/1     Running   0          3d20h
rook-ceph-crashcollector-fb99c26c9cacc869bdac39115adc0b85-vnh64   1/1     Running   0          3d20h
rook-ceph-mds-ocs-storagecluster-cephfilesystem-a-b77b88d9jjnmf   2/2     Running   0          3d20h
rook-ceph-mds-ocs-storagecluster-cephfilesystem-b-75759dc8m2tss   2/2     Running   0          3d20h
rook-ceph-mgr-a-858b667ccd-wlkkv                                  2/2     Running   0          3d20h
rook-ceph-mon-a-89479745b-25kcs                                   2/2     Running   3          3d20h
rook-ceph-mon-b-88765447f-zkhzv                                   2/2     Running   0          3d20h
rook-ceph-mon-c-58959c8547-zf9km                                  2/2     Running   1          3d20h
rook-ceph-operator-86df4b6767-hds8t                               1/1     Running   0          3d20h
rook-ceph-osd-0-6c87558c48-g6l4m                                  2/2     Running   0          3d20h
rook-ceph-osd-1-7f96fd8f74-p9z94                                  2/2     Running   0          3d20h
rook-ceph-osd-2-6c5669c6d8-mh5rw                                  2/2     Running   0          3d20h
rook-ceph-rgw-ocs-storagecluster-cephobjectstore-a-68bd987xv2n5   2/2     Running   0          2d19h
rook-ceph-tools-7d7f64dbb6-j7znt                                  1/1     Running   0          3d3h
```

**Comment by liranmauda** [comment]
Hi @msmiths 
That Is a known issue that was fixed in the operator master: https://github.com/noobaa/noobaa-operator/pull/666
It was also backported to operator 5.8: https://github.com/noobaa/noobaa-operator/pull/667
And is planned to be backported to 5.7

**Comment by liranmauda** [comment]
HI @msmiths 
Just following, Is this issue still happens for you?
If not I think we can close it (we can always reopen if reoccur).

**Comment by msmiths** [comment]
@liranmauda Yes, this error still occurs. But then nothing has changed in my environment. Since I am picking up NooBaa via the OpenShift Container Storage operator, I will have to wait until the operator is updated to pickup a version of NooBaa that includes the fix.

**Comment by nimrod-becker** [comment]
NooBaa UI is no longer supported
